spring.application.name=wcc-postcode-distance-calculator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
app.postcode.csv.path=postcodes-sample.csv
